### ISSUE TITLE
Earth death spawn location

### ISSUE THREAD

**Issue by MonsterMilo** [BlocklandsMC/Issues#2]
**Describe the bug**
When you die on earth you respawn at your last set spawn (bed, respawn anchor, etc.) instead if respawning at spawn

**To Reproduce**
1. Go on Earth
2. Die in any way (by a player, fall damage, etc.)
3. You will respawn at your last set spawn instead of at /spawn

**Expected Behavior**
When dying on earth you should respawn at /spawn

**Actual Behavior**
When dying on earth you respawn at your last set spawn

**Add the following information if relevant**
 - Platform: Java and Bedrock
 - Username not relevant 
 - Gamemode: Earth

**Additional context**

**Comment by nf-projects** [comment]
I was going to fix this by force teleporting players to spawn after they die, on second thought I'm going to hold off on this issue and A/B test spawn vs last set spawn to see which is better. 

@MonsterMilo what happens if you don't have any spawn set?

**Comment by MonsterMilo** [comment]
> I was going to fix this by force teleporting players to spawn after they die, on second thought I'm going to hold off on this issue and A/B test spawn vs last set spawn to see which is better.
> 
> @MonsterMilo what happens if you don't have any spawn set?

https://user-images.githubusercontent.com/108966405/178160856-429e8a02-c63f-4658-a512-7e13efaad058.mov



@nf-projects when you die without a spawnpoint you spawn at the world set spawn (NOT /SPAWN)

**Comment by nf-projects** [comment]
Fixed, a combination of deluxecombat, essentials, and lands were all overriding spawn behavior
